### ISSUE TITLE
Incorrect page count

### ISSUE THREAD

**Issue by camilstaps** [ETCBC/shebanq#1]
The list with occurrences of [יסד](https://shebanq.ancient-data.org/hebrew/word?id=1JSDv&mr=r&qw=w) (version 2017) contains 41 occurrences in 40 verses, hence two pages. On the second page, this is displayed correctly. However, on the first page it says "41 occurrences in 40 verses on **3** pages".

**Comment by charlesLoder** [comment]
I see "42 occurrences in 41 verses on 3 pages" and there are three pages.
Maybe it was fixed?

**Comment by camilstaps** [comment]
@charlesLoder no, it is still the same. Perhaps you do not have the interface set to use version 2017.

**Comment by camilstaps** [comment]
The results for this query on version 2017 are "126 words in 60 verses on 4 pages". You can go to the fourth page, but it is empty.

```
select all objects where
[clause
  [word focus lex="PNH/"]
  ..
  [word focus lex="PNH/"]
]
```

**Comment by dirkroorda** [comment]
Yes, you are right, @camilstaps.
I see a one-liner fix.

**Comment by dirkroorda** [comment]
That was it. Fixed.
It was only the page count, not the number of verses in the result.
It only occurred if the number of verses is an exact multiple of the number of verses per page (20, 40, 60, etc).
Thanks for spotting this and apologies for my complete overlooking this.

**Comment by camilstaps** [comment]
Thanks! No problem, it wasn't really problematic :)
